# Generated by Django 5.2 on 2025-04-27 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodlePlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(unique=True)),
                ('api_key', models.CharField(max_length=100)),
                ('api_endpoint', models.CharField(default='/webservice/rest/server.php', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Moodle Platform',
                'verbose_name_plural': 'Moodle Platforms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MoodleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moodle_username', models.CharField(blank=True, max_length=100, null=True)),
                ('moodle_userid', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPlatformAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_userid', models.IntegerField()),
                ('platform_username', models.CharField(max_length=100)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moodle_management.moodleplatform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moodle_management.moodleuser')),
            ],
            options={
                'unique_together': {('user', 'platform')},
            },
        ),
        migrations.AddField(
            model_name='moodleuser',
            name='platforms',
            field=models.ManyToManyField(through='moodle_management.UserPlatformAssociation', to='moodle_management.moodleplatform'),
        ),
    ]
